// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "org": {
    "nameFull": "Bolalar ijodkorligi ijodiy birlashmasi",
    "nameShort": "BIIB",
    "tagline": "Bolalar va oʻsmirlar ijodini qoʻllab-quvvatlaydigan ijodiy birlashma."
  },
  "nav": {
    "primary": "Asosiy menyu",
    "menuTitle": "Menyu",
    "openMenu": "Menyuni ochish",
    "closeMenu": "Menyuni yopish",
    "skipToContent": "Asosiy qismga oʻtish",
    "home": "Bosh sahifa",
    "about": "Biz haqimizda",
    "projects": "Loyihalar",
    "news": "Yangiliklar",
    "council": "Ekspertlar kengashi",
    "leadership": "Rahbariyat",
    "partners": "Hamkorlar",
    "contacts": "Aloqa"
  },
  "locale": {
    "label": "Tilni tanlash"
  },
  "common": {
    "all": "Barchasi",
    "backToNews": "Yangiliklarga qaytish",
    "opensInNewTab": "yangi oynada ochiladi",
    "topic": "Mavzu",
    "close": "Yopish"
  },
  "home": {
    "hero": {
      "titleStart": "Bolalar ijodi uchun katta",
      "titleAccent": "sahna",
      "subtitle": "Kasting, studiya, koʻrgazma va festival. Har bir bola oʻz ovozini, rangini va sahnasini topsin deb ishlaymiz.",
      "ctaPrimary": "Loyihaga qoʻshilish",
      "ctaSecondary": "Loyihalar",
      "scrollCue": "Pastga"
    },
    "flagship": {
      "heading": "UPOP TREND",
      "lead": "Birlashmaning bosh loyihasi. Butun mamlakat boʻylab oʻtadigan qoʻshiqchilik kastingi: viloyat tanlovlaridan poytaxt sahnasigacha ovoz, mashgʻulot va jonli chiqish.",
      "cta": "Batafsil",
      "bannerAlt": "UPOP TREND ishtirokchilari: milliy liboslarda toʻrt qiz, dutor, doira va mikrofon bilan"
    },
    "projects": {
      "heading": "Bizning loyihalar",
      "all": "Barchasi",
      "lead": "Toʻrt yoʻnalish, toʻrt boshqa xil ish. Har birining oʻz sahnasi, oʻz ustozlari va oʻz rangi bor."
    },
    "about": {
      "heading": "Biz haqimizda",
      "p1": "Birlashma bolalar va oʻsmirlarga ijod bilan shugʻullanish uchun joy, ustoz va sahna beradi. Mashgʻulotlar bepul, tanlovlar ochiq.",
      "p2": "Biz viloyat markazlaridan tortib kichik tumanlargacha ishlaymiz: studiya ochamiz, oʻqituvchilarni tayyorlaymiz, koʻrgazma va festivallarni oʻtkazamiz.",
      "p3": "Bola ijodga kelganda oʻzini boshqacha koʻrsatadi. Bizning ishimiz shu payt uni yolgʻiz qoldirmaslik.",
      "cta": "Koʻproq"
    },
    "news": {
      "heading": "Yangiliklar",
      "all": "Barchasi"
    },
    "people": {
      "heading": "Ekspertlar kengashi",
      "lead": "Tanlovlarni baholaydigan va dasturlarni tasdiqlaydigan mutaxassislar.",
      "all": "Aʼzolar",
      "leadership": "Rahbariyat"
    },
    "partners": {
      "heading": "Hamkorlar",
      "lead": "Loyihalarimiz davlat idoralari, taʼlim muassasalari va xususiy tashkilotlar bilan birga amalga oshiriladi."
    },
    "closing": {
      "heading": "Ijodingizni biz bilan boshlang",
      "lead": "Ariza qoldiring: yaqin studiya, tanlov muddati va keyingi qadam haqida javob yozamiz.",
      "cta": "Qoʻshilish"
    }
  },
  "about": {
    "title": "Biz haqimizda",
    "lead": "Bolalar ijodkorligi ijodiy birlashmasi bolalar va oʻsmirlarning ijodiy qobiliyatini ochish uchun tuzilgan.",
    "missionHeading": "Maqsadimiz",
    "missionBody": "Har bir bolaga ijod bilan shugʻullanish imkoni boʻlsin. Buning uchun yaqin joyda studiya, tayyorlangan ustoz va haqiqiy sahna kerak. Biz shu uchtasini bir joyga yigʻamiz.",
    "historyHeading": "Qanday boshlangan",
    "historyBody1": "Birlashma bir necha shahar studiyasining birgalikdagi koʻrgazmasidan oʻsib chiqdi. Oʻshanda maʼlum boʻldiki, bolalar koʻp, ustozlar bor, ammo ularni bir-biriga ulaydigan tizim yoʻq.",
    "historyBody2": "Bugun birlashma toʻrt yoʻnalishda ishlaydi va yiliga bir necha ming bolani qamrab oladi. Eng yirigi — UPOP TREND kastingi.",
    "valuesHeading": "Nimaga tayanamiz",
    "values": {
      "openHeading": "Ochiqlik",
      "openBody": "Tanlovga hujjat, tavsiya yoki toʻlov kerak emas. Ariza va ishtirok yetarli.",
      "craftHeading": "Ustozlik",
      "craftBody": "Bolani baholash oson, oʻrgatish qiyin. Biz oʻqituvchilarni tayyorlashga vaqt sarflaymiz.",
      "stageHeading": "Sahna",
      "stageBody": "Chizilgan rasm devorga, aytilgan qoʻshiq sahnaga chiqishi kerak. Aks holda mashgʻulot yarim qoladi.",
      "regionHeading": "Hudud",
      "regionBody": "Poytaxtdan tashqarida ham bir xil dastur, bir xil ustoz va bir xil imkon."
    }
  },
  "projects": {
    "title": "Loyihalar",
    "lead": "Har bir loyihaning oʻz yoshi, oʻz mashgʻuloti va oʻz yakuni bor. Quyida toʻrttasi.",
    "factsLabel": "Qisqacha",
    "visitSite": "Saytga oʻtish",
    "playVideo": "Videoni koʻrish",
    "videoCaption": "Loyiha muhokamasi"
  },
  "news": {
    "title": "Yangiliklar",
    "lead": "Tanlov muddatlari, koʻrgazmalar va birlashma ishidagi oʻzgarishlar.",
    "empty": "Hozircha yangilik yoʻq.",
    "published": "Eʼlon qilingan",
    "otherNews": "Boshqa yangiliklar"
  },
  "council": {
    "title": "Ekspertlar kengashi",
    "lead": "Kengash tanlov shartlarini tasdiqlaydi, ishlarni baholaydi va oʻquv dasturlarini koʻrib chiqadi.",
    "roleLabel": "Yoʻnalish"
  },
  "leadership": {
    "title": "Rahbariyat",
    "lead": "Birlashmaning kundalik ishini olib boradigan jamoa.",
    "roleLabel": "Lavozim"
  },
  "partners": {
    "title": "Hamkorlar",
    "lead": "Birgalikda studiya ochamiz, tanlov oʻtkazamiz va bolalarni sahnaga olib chiqamiz.",
    "becomeHeading": "Hamkor boʻlish",
    "becomeBody": "Tashkilotingiz bolalar ijodini qoʻllab-quvvatlashni istasa, aloqa sahifasidan yozing.",
    "becomeCta": "Yozish",
    "slot": "Hamkor tashkilot {n}"
  },
  "contacts": {
    "title": "Aloqa",
    "lead": "Savol, taklif yoki hamkorlik boʻyicha quyidagi shakl orqali yozing yoki toʻgʻridan-toʻgʻri qoʻngʻiroq qiling.",
    "addressLabel": "Manzil",
    "phoneLabel": "Telefon",
    "emailLabel": "Elektron pochta",
    "hoursLabel": "Ish vaqti",
    "socialLabel": "Ijtimoiy tarmoqlar",
    "formHeading": "Xabar yuborish"
  },
  "form": {
    "name": "Ismingiz",
    "namePlaceholder": "Ism va familiya",
    "email": "Elektron pochta",
    "emailPlaceholder": "ism@pochta.uz",
    "phone": "Telefon",
    "phonePlaceholder": "+998 90 000 00 00",
    "phoneHint": "Ixtiyoriy",
    "topic": "Mavzu",
    "topicPlaceholder": "Studiyaga yozilish",
    "message": "Xabar",
    "messagePlaceholder": "Qisqacha yozing: kim, qayerdan va nima haqida.",
    "submit": "Yuborish",
    "submitting": "Yuborilmoqda",
    "successHeading": "Xabar yuborildi",
    "successBody": "Rahmat. Ish kunlari ichida javob yozamiz.",
    "errorHeading": "Yuborilmadi",
    "errorBody": "Ulanishda xatolik boʻldi. Birozdan soʻng qayta urinib koʻring yoki toʻgʻridan-toʻgʻri yozing.",
    "required": "Bu maydon toʻldirilishi kerak.",
    "invalidEmail": "Pochta manzili toʻgʻri emas.",
    "tooShort": "Kamida {min} belgi kerak.",
    "tooLong": "Koʻpi bilan {max} belgi.",
    "errorSummary": "Shaklda xatolik bor. Quyidagi maydonlarni tekshiring."
  },
  "footer": {
    "navHeading": "Sahifalar",
    "projectsHeading": "Loyihalar",
    "contactsHeading": "Aloqa",
    "rights": "Barcha huquqlar himoyalangan.",
    "privacy": "Maxfiylik siyosati",
    "credit": "Designed & Developed by teiior"
  },
  "legal": {
    "privacyTitle": "Maxfiylik siyosati",
    "privacyLead": "Bu sahifada saytda qanday maʼlumot yigʻilishi va u nima uchun kerakligi yozilgan.",
    "collectHeading": "Nima yigʻiladi",
    "collectBody": "Faqat aloqa shaklida oʻzingiz yozgan maʼlumot: ism, elektron pochta, telefon (agar kiritsangiz), mavzu va xabar matni. Sayt boshqa hech narsa soʻramaydi.",
    "useHeading": "Nima uchun ishlatiladi",
    "useBody": "Yagona maqsad — xabaringizga javob berish. Maʼlumot reklama uchun ishlatilmaydi va uchinchi shaxslarga berilmaydi.",
    "storeHeading": "Qayerda saqlanadi",
    "storeBody": "Shakl orqali yuborilgan xabar birlashmaning ichki kanaliga uzatiladi. Saytning oʻzida maʼlumotlar bazasi yoʻq va hech narsa saqlanmaydi.",
    "cookiesHeading": "Cookie va brauzer xotirasi",
    "cookiesBody": "Bitta cookie tanlagan tilingizni eslab qoladi. Mavzu tanlovi (yorugʻ yoki qorongʻi) brauzeringizda saqlanadi va serverga yuborilmaydi. Tahlil tizimlari va reklama kuzatuvchilari ishlatilmaydi.",
    "rightsHeading": "Maʼlumotingizni oʻchirish",
    "rightsBody": "Yozishmangizni oʻchirishni soʻrash uchun quyidagi pochtaga xabar yuboring. Soʻrov ish kunlari ichida bajariladi."
  },
  "meta": {
    "homeTitle": "Bosh sahifa",
    "homeDescription": "Bolalar ijodkorligi ijodiy birlashmasi: kasting, studiya, koʻrgazma va festival. UPOP TREND milliy kastingi.",
    "aboutDescription": "Birlashmaning maqsadi, tarixi va qadriyatlari.",
    "projectsDescription": "Birlashmaning toʻrt yoʻnalishi: UPOP TREND, Rangli olam, Sahna bolalari, Ertak ustaxonasi.",
    "newsDescription": "Tanlov muddatlari, koʻrgazmalar va birlashma yangiliklari.",
    "councilDescription": "Ekspertlar kengashi aʼzolari va ularning yoʻnalishlari.",
    "leadershipDescription": "Birlashma rahbariyati.",
    "partnersDescription": "Birlashmaning hamkor tashkilotlari.",
    "contactsDescription": "Manzil, telefon, elektron pochta va xabar yuborish shakli."
  },
  "notFound": {
    "title": "Sahifa topilmadi",
    "lead": "Havola eskirgan yoki manzilda xatolik bor.",
    "cta": "Bosh sahifaga"
  },
  "error": {
    "title": "Nimadir buzildi",
    "lead": "Sahifani yuklashda xatolik yuz berdi.",
    "retry": "Qayta urinish"
  },
  "appearance": {
    "label": "Koʻrinish sozlamalari",
    "themeHeading": "Mavzu",
    "themeSystem": "Tizim",
    "themeLight": "Yorugʻ",
    "themeDark": "Qorongʻi",
    "glassHeading": "Shaffoflik",
    "glassDense": "Zich",
    "glassStandard": "Odatdagi",
    "glassClear": "Shaffof",
    "systemOverride": "Tizimda shaffoflik kamaytirilgan, shuning uchun sozlama ishlamaydi."
  }
};
export default messages;