import type { Person } from "./types";

/**
 * Ekspertlar kengashi. Sohalar ustavdagi ijodiy yoʻnalishlar boʻyicha (6.10-band): adabiyot, teatr,
 * kino va animatsiya, musiqa, tasviriy sanʼat, media va raqamli ijod. Ism, surat va qisqacha maʼlumot
 * tashkilotdan kutilmoqda.
 */
export const EXPERTS: readonly Person[] = [
  {
    id: "expert-1",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Adabiyot",
      oz: "Адабиёт",
      ozbekca: "Adabiyot",
      ru: "Литература",
      en: "Literature",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-2",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Teatr",
      oz: "Театр",
      ozbekca: "Teatr",
      ru: "Театр",
      en: "Theatre",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-3",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Kino va animatsiya",
      oz: "Кино ва анимация",
      ozbekca: "Kino va animatsiya",
      ru: "Кино и анимация",
      en: "Film and animation",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-4",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Musiqa",
      oz: "Мусиқа",
      ozbekca: "Musiqa",
      ru: "Музыка",
      en: "Music",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-5",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Tasviriy sanʼat",
      oz: "Тасвирий санъат",
      ozbekca: "Tasviriy sanʼat",
      ru: "Изобразительное искусство",
      en: "Fine art",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-6",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Media va raqamli ijod",
      oz: "Медиа ва рақамли ижод",
      ozbekca: "Media va raqamli ijod",
      ru: "Медиа и цифровое творчество",
      en: "Media and digital creativity",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
];
