import type { Person } from "./types";

/**
 * Ekspertlar kengashi. Ism, surat va qisqacha maʼlumot tashkilotdan kelmagan: faqat soha koʻrsatiladi.
 * Oldingi saytdagi ismlar oʻrinbosar edi, ular olib tashlandi.
 */
export const EXPERTS: readonly Person[] = [
  {
    id: "expert-1",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Tasviriy sanʼat",
      oz: "Тасвирий санъат",
      ozbekca: "Tasviriy sanʼat",
      ru: "Изобразительное искусство",
      en: "Fine art",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-2",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Musiqa va vokal",
      oz: "Мусиқа ва вокал",
      ozbekca: "Musiqa va vokal",
      ru: "Музыка и вокал",
      en: "Music and voice",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-3",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Teatr va sahna nutqi",
      oz: "Театр ва саҳна нутқи",
      ozbekca: "Teatr va sahna nutqi",
      ru: "Театр и сценическая речь",
      en: "Theatre and stage speech",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-4",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Adabiyot",
      oz: "Адабиёт",
      ozbekca: "Adabiyot",
      ru: "Литература",
      en: "Literature",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-5",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Animatsiya",
      oz: "Анимация",
      ozbekca: "Animatsiya",
      ru: "Анимация",
      en: "Animation",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "expert-6",
    kind: "expert",
    status: "pending",
    name: null,
    role: {
      uz: "Kengash aʼzosi",
      oz: "Кенгаш аъзоси",
      ozbekca: "Kengaş aʼzosi",
      ru: "Член совета",
      en: "Council member",
    },
    field: {
      uz: "Pedagogika",
      oz: "Педагогика",
      ozbekca: "Pedagogika",
      ru: "Педагогика",
      en: "Teaching",
    },
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
];
