import type { Person } from "./types";

/** Rahbariyat. Lavozimlar tuzilmaviy, ism va surat tashkilotdan kelishi kerak. */
export const LEADERSHIP: readonly Person[] = [
  {
    id: "leader-1",
    kind: "leader",
    status: "pending",
    name: null,
    role: {
      uz: "Direktor",
      oz: "Директор",
      ozbekca: "Direktor",
      ru: "Директор",
      en: "Director",
    },
    field: null,
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "leader-2",
    kind: "leader",
    status: "pending",
    name: null,
    role: {
      uz: "Loyihalar boʻyicha direktor oʻrinbosari",
      oz: "Лойиҳалар бўйича директор ўринбосари",
      ozbekca: "Loyihalar böyiça direktor örinbosari",
      ru: "Заместитель директора по проектам",
      en: "Deputy Director for Projects",
    },
    field: null,
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "leader-3",
    kind: "leader",
    status: "pending",
    name: null,
    role: {
      uz: "Hududiy studiyalar boshligʻi",
      oz: "Ҳудудий студиялар бошлиғи",
      ozbekca: "Hududiy studiyalar boşliği",
      ru: "Руководитель региональных студий",
      en: "Head of Regional Studios",
    },
    field: null,
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
  {
    id: "leader-4",
    kind: "leader",
    status: "pending",
    name: null,
    role: {
      uz: "Matbuot kotibi",
      oz: "Матбуот котиби",
      ozbekca: "Matbuot kotibi",
      ru: "Пресс-секретарь",
      en: "Press Secretary",
    },
    field: null,
    bio: null,
    photo: null,
    reception: null,
    email: null,
  },
];
