import type { Person } from "./types";

/**
 * ODAMLAR — mijozdan keladigan maʼlumot: ism, lavozim va surat.
 * Quyidagi ism-şariflar örinbosar; surat maydoni böş bölsa çizma körsatiladi.
 */
export const PEOPLE: readonly Person[] = [
  {
    id: "council-1",
    kind: "council",
    name: {
      "uz-Latn": "Nodira Ahmedova",
      "uz-Cyrl": "Нодира Аҳмедова",
      "uz-Latn-x-reform": "Nodira Ahmedova",
      ru: "Нодира Ахмедова",
      en: "Nodira Ahmedova",
    },
    role: {
      "uz-Latn": "Tasviriy sanʼat",
      "uz-Cyrl": "Тасвирий санъат",
      "uz-Latn-x-reform": "Tasviriy sanʼat",
      ru: "Изобразительное искусство",
      en: "Fine art",
    },
    bio: {
      "uz-Latn": "Rasm studiyalarining oʻquv dasturini koʻrib chiqadi va koʻrgazmalarga ish tanlaydi.",
      "uz-Cyrl": "Расм студияларининг ўқув дастурини кўриб чиқади ва кўргазмаларга иш танлайди.",
      "uz-Latn-x-reform": "Rasm studiyalarining öquv dasturini körib çiqadi va körgazmalarga iş tanlaydi.",
      ru: "Рассматривает учебные программы художественных студий и отбирает работы на выставки.",
      en: "Reviews the study programme of the drawing studios and selects the work for the exhibitions.",
    },
  },
  {
    id: "council-2",
    kind: "council",
    name: {
      "uz-Latn": "Sardor Yoʻldoshev",
      "uz-Cyrl": "Сардор Йўлдошев",
      "uz-Latn-x-reform": "Sardor Yöldoşev",
      ru: "Сардор Юлдашев",
      en: "Sardor Yoʻldoshev",
    },
    role: {
      "uz-Latn": "Musiqa va vokal",
      "uz-Cyrl": "Мусиқа ва вокал",
      "uz-Latn-x-reform": "Musiqa va vokal",
      ru: "Музыка и вокал",
      en: "Music and voice",
    },
    bio: {
      "uz-Latn": "Kasting bosqichlarida ovozni baholaydi, tayyorgarlik mashgʻulotlarini rejalashtiradi.",
      "uz-Cyrl": "Кастинг босқичларида овозни баҳолайди, тайёргарлик машғулотларини режалаштиради.",
      "uz-Latn-x-reform": "Kasting bosqiçlarida ovozni baholaydi, tayyorgarlik maşğulotlarini rejalaştiradi.",
      ru: "Оценивает голоса на этапах кастинга и планирует подготовительные занятия.",
      en: "Judges the voices at the audition rounds and plans the preparation classes.",
    },
  },
  {
    id: "council-3",
    kind: "council",
    name: {
      "uz-Latn": "Dilnoza Rahimova",
      "uz-Cyrl": "Дилноза Раҳимова",
      "uz-Latn-x-reform": "Dilnoza Rahimova",
      ru: "Дилноза Рахимова",
      en: "Dilnoza Rahimova",
    },
    role: {
      "uz-Latn": "Teatr va sahna nutqi",
      "uz-Cyrl": "Театр ва саҳна нутқи",
      "uz-Latn-x-reform": "Teatr va sahna nutqi",
      ru: "Театр и сценическая речь",
      en: "Theatre and stage speech",
    },
    bio: {
      "uz-Latn": "Teatr guruhlarining mavsumiy dasturini tasdiqlaydi va spektakllarni koʻrib chiqadi.",
      "uz-Cyrl": "Театр гуруҳларининг мавсумий дастурини тасдиқлайди ва спектаклларни кўриб чиқади.",
      "uz-Latn-x-reform": "Teatr guruhlarining mavsumiy dasturini tasdiqlaydi va spektakllarni körib çiqadi.",
      ru: "Утверждает сезонные программы театральных групп и просматривает спектакли.",
      en: "Approves the seasonal programme of the theatre groups and reviews the plays.",
    },
  },
  {
    id: "council-4",
    kind: "council",
    name: {
      "uz-Latn": "Jasur Karimov",
      "uz-Cyrl": "Жасур Каримов",
      "uz-Latn-x-reform": "Jasur Karimov",
      ru: "Жасур Каримов",
      en: "Jasur Karimov",
    },
    role: {
      "uz-Latn": "Adabiyot",
      "uz-Cyrl": "Адабиёт",
      "uz-Latn-x-reform": "Adabiyot",
      ru: "Литература",
      en: "Literature",
    },
    bio: {
      "uz-Latn": "Yosh mualliflarning matnlarini oʻqiydi va ustaxona dasturiga takliflar beradi.",
      "uz-Cyrl": "Ёш муаллифларнинг матнларини ўқийди ва устахона дастурига таклифлар беради.",
      "uz-Latn-x-reform": "Yoş mualliflarning matnlarini öqiydi va ustaxona dasturiga takliflar beradi.",
      ru: "Читает тексты юных авторов и предлагает изменения в программу мастерской.",
      en: "Reads the texts of young authors and puts suggestions to the workshop programme.",
    },
  },
  {
    id: "council-5",
    kind: "council",
    name: {
      "uz-Latn": "Malika Toʻxtayeva",
      "uz-Cyrl": "Малика Тўхтаева",
      "uz-Latn-x-reform": "Malika Töxtayeva",
      ru: "Малика Тухтаева",
      en: "Malika Toʻxtayeva",
    },
    role: {
      "uz-Latn": "Animatsiya",
      "uz-Cyrl": "Анимация",
      "uz-Latn-x-reform": "Animatsiya",
      ru: "Анимация",
      en: "Animation",
    },
    bio: {
      "uz-Latn": "Multfilm ishlarini texnik va badiiy tomondan baholaydi.",
      "uz-Cyrl": "Мультфильм ишларини техник ва бадиий томондан баҳолайди.",
      "uz-Latn-x-reform": "Multfilm işlarini texnik va badiiy tomondan baholaydi.",
      ru: "Оценивает мультипликационные работы с технической и художественной стороны.",
      en: "Assesses the animated work on both the technical and the artistic side.",
    },
  },
  {
    id: "council-6",
    kind: "council",
    name: {
      "uz-Latn": "Bekzod Nazarov",
      "uz-Cyrl": "Бекзод Назаров",
      "uz-Latn-x-reform": "Bekzod Nazarov",
      ru: "Бекзод Назаров",
      en: "Bekzod Nazarov",
    },
    role: {
      "uz-Latn": "Pedagogika",
      "uz-Cyrl": "Педагогика",
      "uz-Latn-x-reform": "Pedagogika",
      ru: "Педагогика",
      en: "Teaching",
    },
    bio: {
      "uz-Latn": "Ustozlar uchun seminar dasturini tuzadi, guruh bilan ishlash usullarini kuzatadi.",
      "uz-Cyrl": "Устозлар учун семинар дастурини тузади, гуруҳ билан ишлаш усулларини кузатади.",
      "uz-Latn-x-reform": "Ustozlar uçun seminar dasturini tuzadi, guruh bilan işlaş usullarini kuzatadi.",
      ru: "Составляет программу семинаров для наставников и следит за методами работы с группой.",
      en: "Puts together the seminar programme for mentors and watches how they work with a group.",
    },
  },
  {
    id: "lead-1",
    kind: "leadership",
    name: {
      "uz-Latn": "Ozoda Ergasheva",
      "uz-Cyrl": "Озода Эргашева",
      "uz-Latn-x-reform": "Ozoda Ergaşeva",
      ru: "Озода Эргашева",
      en: "Ozoda Ergasheva",
    },
    role: {
      "uz-Latn": "Direktor",
      "uz-Cyrl": "Директор",
      "uz-Latn-x-reform": "Direktor",
      ru: "Директор",
      en: "Director",
    },
    bio: {
      "uz-Latn": "Birlashmaning umumiy ishini boshqaradi, hamkorlik kelishuvlarini olib boradi.",
      "uz-Cyrl": "Бирлашманинг умумий ишини бошқаради, ҳамкорлик келишувларини олиб боради.",
      "uz-Latn-x-reform": "Birlaşmaning umumiy işini boşqaradi, hamkorlik kelişuvlarini olib boradi.",
      ru: "Руководит общей работой объединения и ведёт партнёрские соглашения.",
      en: "Runs the general work of the association and handles the partnership agreements.",
    },
  },
  {
    id: "lead-2",
    kind: "leadership",
    name: {
      "uz-Latn": "Rustam Sobirov",
      "uz-Cyrl": "Рустам Собиров",
      "uz-Latn-x-reform": "Rustam Sobirov",
      ru: "Рустам Сабиров",
      en: "Rustam Sobirov",
    },
    role: {
      "uz-Latn": "Loyihalar boʻyicha direktor oʻrinbosari",
      "uz-Cyrl": "Лойиҳалар бўйича директор ўринбосари",
      "uz-Latn-x-reform": "Loyihalar böyiça direktor örinbosari",
      ru: "Заместитель директора по проектам",
      en: "Deputy Director for Projects",
    },
    bio: {
      "uz-Latn": "Toʻrt yoʻnalishdagi loyihalarning rejasi va muddatlari uchun javob beradi.",
      "uz-Cyrl": "Тўрт йўналишдаги лойиҳаларнинг режаси ва муддатлари учун жавоб беради.",
      "uz-Latn-x-reform": "Tört yönalişdagi loyihalarning rejasi va muddatlari uçun javob beradi.",
      ru: "Отвечает за планы и сроки проектов по всем четырём направлениям.",
      en: "Answers for the plans and the dates of the projects in all four directions.",
    },
  },
  {
    id: "lead-3",
    kind: "leadership",
    name: {
      "uz-Latn": "Gulnora Qodirova",
      "uz-Cyrl": "Гулнора Қодирова",
      "uz-Latn-x-reform": "Gulnora Qodirova",
      ru: "Гульнора Кадырова",
      en: "Gulnora Qodirova",
    },
    role: {
      "uz-Latn": "Hududiy studiyalar boshligʻi",
      "uz-Cyrl": "Ҳудудий студиялар бошлиғи",
      "uz-Latn-x-reform": "Hududiy studiyalar boşliği",
      ru: "Руководитель региональных студий",
      en: "Head of Regional Studios",
    },
    bio: {
      "uz-Latn": "Viloyatlardagi studiyalarning ochilishi va taʼminoti bilan shugʻullanadi.",
      "uz-Cyrl": "Вилоятлардаги студияларнинг очилиши ва таъминоти билан шуғулланади.",
      "uz-Latn-x-reform": "Viloyatlardagi studiyalarning oçilişi va taʼminoti bilan şuğullanadi.",
      ru: "Занимается открытием и обеспечением студий в областях.",
      en: "Looks after the opening and the supply of the studios in the regions.",
    },
  },
  {
    id: "lead-4",
    kind: "leadership",
    name: {
      "uz-Latn": "Shohruh Islomov",
      "uz-Cyrl": "Шоҳруҳ Исломов",
      "uz-Latn-x-reform": "Şohruh Islomov",
      ru: "Шохрух Исламов",
      en: "Shohruh Islomov",
    },
    role: {
      "uz-Latn": "Matbuot kotibi",
      "uz-Cyrl": "Матбуот котиби",
      "uz-Latn-x-reform": "Matbuot kotibi",
      ru: "Пресс-секретарь",
      en: "Press Secretary",
    },
    bio: {
      "uz-Latn": "Yangiliklar, ijtimoiy tarmoqlar va ommaviy axborot vositalari bilan aloqa.",
      "uz-Cyrl": "Янгиликлар, ижтимоий тармоқлар ва оммавий ахборот воситалари билан алоқа.",
      "uz-Latn-x-reform": "Yangiliklar, ijtimoiy tarmoqlar va ommaviy axborot vositalari bilan aloqa.",
      ru: "Новости, соцсети и работа со средствами массовой информации.",
      en: "News, social media and contact with the press.",
    },
  },
];
