/** UPOP TREND loyihasi va uning galereyasi tahrirlari matnlari. */
export const UPOP_COPY = {
  project: {
    groups: {
      basics: "Holat va yosh",
      facts: "Faktlar",
      cost: "Narx",
      register: "Roʻyxatdan oʻtish",
      highlights: "Asosiy dalillar",
      media: "Videolar va tavsiflar",
    },
    statusHint: {
      confirmed: "Loyiha sahifasi qidiruv tizimlariga ochiq.",
      draft: "Saytda koʻrinadi, lekin loyiha sahifasi qidiruvdan yopiq.",
      pending: "Maʼlumot kutilmoqda: sahifa qidiruvdan yopiq.",
    },
    status: "Holati",
    ageFrom: "Yoshi: dan",
    ageTo: "Yoshi: gacha",
    ageStatus: "Yosh",
    ageHint: "Saytda «14–19 yosh» koʻrinishida chiqadi.",
    facts: { format: "Shakli", place: "Joyi", schedule: "Jadvali", teacher: "Ustozlar" },
    factHint: "Boʻsh qolsa, saytda uning oʻrnida vaqtinchalik toʻldiruvchi matn turadi.",
    cost: "Ishtirok narxi",
    costOptions: { free: "Bepul", paid: "Pullik", unknown: "Nomaʼlum" },
    costHints: {
      free: "Saytda «Bepul» deb yoziladi.",
      paid: "Saytda narx oʻrnida vaqtinchalik toʻldiruvchi matn turadi.",
      unknown: "Hali aniq emas.",
    },
    externalHref: "Roʻyxatdan oʻtish havolasi",
    externalHrefHint: "Tugma shu manzilni yangi oynada ochadi.",
    externalLabel: "Havola yorligʻi",
    externalLabelHint: "Qisqa manzil, masalan upop.uz.",
    highlightsHint:
      "Bosh sahifadagi UPOP boʻlimida uchtagacha qisqa dalil. Har biri beshta tilda, belgisi tartibga bogʻliq.",
    highlight: "{n}-dalil",
    highlightText: "Matni",
    highlightAdd: "Dalil qoʻshish",
    highlightRemove: "{n}-dalilni olib tashlash",
    highlightMax: "Uchtadan ortiq dalil qoʻshilmaydi.",
    videoNote: "Videolar hozircha kodda boshqariladi: bu yerda faqat tavsiflari oʻzgaradi.",
    roles: { loop: "Sahna halqasi", film: "Film", wordmark: "Logotip" },
    altOf: "{role}: tavsif",
    altHint: "Koʻrmaydiganlar uchun: kadrda nima borligi.",
    file: "Fayl: {name}",
    ageOrder: "«Gacha» «dan»dan kichik boʻlmasin.",
    ageRange: "Yosh 3 dan 30 gacha.",
  },
  gallery: {
    intro:
      "UPOP TREND sahifasidagi 8 joyli galereya. Saytda toʻr shu tartibda: 1-joy eng katta ramka. Hech bir joy toʻlmasa, galereya saytda koʻrinmaydi.",
    map: "Saytdagi galereya tuzilishi (kompyuterda). Katakni bossangiz, oʻsha joyga oʻtadi.",
    mapEmpty: "{n}-joy, boʻsh",
    mapFilled: "{n}-joy, {kind}",
    slot: "{n}-joy",
    largest: "eng katta ramka",
    empty: "Boʻsh",
    emptyHint: "Kutubxonadan rasm yoki video tanlang yoki yangi rasm yuklang.",
    defaults: "Ramka: {frame} · harakat: {motion} (keyin oʻzgartirish mumkin).",
    add: "Qoʻshish",
    replace: "Almashtirish",
    clear: "Boʻshatish",
    clearLabel: "{n}-joyni boʻshatish",
    cleared: "{n}-joy boʻshatildi.",
    added: "{n}-joyga qoʻshildi.",
    kinds: { image: "rasm", video: "video" },
    frame: "Ramka",
    frames: {
      stage: "Sahna",
      gold: "Oltin",
      glass: "Oyna",
      ticket: "Chipta",
      film: "Kino lentasi",
      mat: "Paspartu",
    },
    motion: "Harakat",
    motions: {
      curtain: "Parda",
      "slide-end": "Oʻngdan kirish",
      wipe: "Surilib ochilish",
      rise: "Koʻtarilish",
      iris: "Doira ochilish",
      tilt: "Egilish",
      "slide-start": "Chapdan kirish",
      zoom: "Yaqinlashish",
    },
    poster: "Muqova kadri",
    posterHint: "Video yuklanguncha shu rasm turadi.",
    posterPick: "Muqova kadrini tanlash",
    posterMissing: "Video uchun muqova kadri kerak.",
    caption: "Tavsif (ixtiyoriy)",
    captionHint: "Boʻsh qolsa, saytda «UPOP TREND: N-lavha» ishlatiladi.",
    gap: "Oradagi boʻsh joylar saytda qoldirilmaydi: keyingi kadrlar oldinga suriladi va oʻsha joy oʻlchamini oladi.",
    picker: {
      open: "Kutubxonadan tanlash",
      title: "Galereya uchun tanlash",
      description: "Videolar va oxirgi yuklangan rasmlar.",
      videos: "Videolar",
      images: "Rasmlar",
      empty: "Kutubxona boʻsh.",
      item: "{kind}: {name}",
    },
    upload: "Rasm yuklash",
  },
} as const;
