/**
 * Boshqaruv paneli matnlari. Panel bir tilli (oʻzbek lotini), shu sabab lugʻatlarga kirmaydi:
 * u yerda har kalit besh tilda talab qilinadi.
 */
export const ADMIN_COPY = {
  title: "Boshqaruv paneli",
  brand: "Bolalar Ijodkorligi Ijodiy Birlashmasi",
  skipToContent: "Asosiy qismga oʻtish",
  login: {
    title: "Boshqaruv paneli",
    formLabel: "Panelga kirish",
    email: "Elektron pochta",
    password: "Parol",
    showPassword: "Parolni koʻrsatish",
    hidePassword: "Parolni yashirish",
    submit: "Kirish",
    submitting: "Tekshirilmoqda…",
    invalid: "Email yoki parol notoʻgʻri",
    closed: "Panel hali sozlanmagan: server sozlamalari toʻliq emas.",
    required: "majburiy",
  },
  nav: {
    label: "Panel boʻlimlari",
    groups: {
      content: "Kontent",
      people: "Odamlar",
      organization: "Tashkilot",
      system: "Tizim",
    },
    openSite: "Saytni ochish",
    newTab: "yangi oynada ochiladi",
    logout: "Chiqish",
    menu: "Menyu",
    openMenu: "Menyuni ochish",
    closeMenu: "Menyuni yopish",
  },
  pages: {
    dashboard: "Boshqaruv",
    news: "Yangiliklar",
    upop: "UPOP",
    gallery: "Galereya",
    history: "Tarix",
    texts: "Matnlar",
    leadership: "Rahbariyat",
    experts: "Ekspertlar",
    partners: "Hamkorlar",
    contacts: "Aloqa",
    media: "Media",
    journal: "Jurnal",
    security: "Xavfsizlik",
  },
  placeholder: "Bu boʻlim tez orada ishga tushadi.",
  statuses: { confirmed: "Tasdiqlangan", draft: "Qoralama", pending: "Kutilmoqda" },
  common: {
    cancel: "Bekor qilish",
    close: "Yopish",
    yes: "Ha",
    no: "Yoʻq",
    newTab: "yangi oynada ochiladi",
  },
  dashboard: {
    addNews: "Yangilik qoʻshish",
    allNews: "Barcha yangiliklar",
    counts:
      "Yangiliklar: {total} ta · tasdiqlangan {confirmed}, qoralama {draft}, kutilmoqda {pending}",
    recent: "Oxirgi oʻzgarishlar",
    allJournal: "Butun jurnal",
  },
  health: {
    title: "Sayt holati",
    source: "Sahifalar manbai",
    sources: { supabase: "Maʼlumotlar bazasi", bundled: "Repodagi nusxa" },
    reachable: "Bazaga ulanish",
    generatedAt: "Bazadagi nusxa vaqti",
    unknown: "nomaʼlum",
    refresh: "Saytni yangilash",
    refreshing: "Yangilanmoqda…",
    refreshed: "Hamma sahifa yangilanishga yuborildi.",
    refreshHint: "Maʼlumot bazada qoʻlda oʻzgartirilgan boʻlsa, saytga darhol chiqaradi.",
    failed: "Yangilab boʻlmadi. Qayta urinib koʻring.",
  },
  journal: {
    caption: "Kontentdagi oʻzgarishlar, yangisi birinchi",
    empty: "Jurnal hozircha boʻsh.",
    columns: {
      at: "Vaqt",
      entity: "Boʻlim",
      action: "Amal",
      summary: "Qisqacha",
      restore: "Qaytarish",
    },
    entities: {
      news: "Yangilik",
      media: "Rasm",
      person: "Odam",
      partner: "Hamkor",
      milestone: "Tarix",
      contacts: "Aloqa",
      socials: "Ijtimoiy tarmoqlar",
      project: "Loyiha",
      upop_shots: "UPOP galereya",
      text: "Matn",
      allow_words: "Soʻzlar roʻyxati",
      order: "Tartib",
    },
    actions: {
      create: "Yaratildi",
      update: "Oʻzgartirildi",
      delete: "Oʻchirildi",
      restore: "Qaytarildi",
    },
    restore: "Qaytarish",
    restoreLabel: "{summary}: shu oʻzgarishdan oldingi holatga qaytarish",
    restoreTitle: "Oldingi holatga qaytarish",
    restoreText:
      "«{summary}» shu oʻzgarishdan oldingi holatiga qaytadi va saytga darhol chiqadi. Hozirgi holat jurnalda qoladi.",
    restored: "Qaytarildi: sayt bir necha soniyada yangilanadi.",
    missing: "Jurnal yozuvi topilmadi.",
    notRestorable: "Bu yozuvni qaytarib boʻlmaydi.",
    failed: "Qaytarib boʻlmadi. Qayta urinib koʻring.",
    older: "Oldingi yozuvlar",
    newest: "Eng yangilari",
  },
  errors: {
    notFound: "Sahifa topilmadi",
    notFoundText: "Panelda bunday boʻlim yoʻq.",
    backHome: "Boshqaruvga qaytish",
    staleTitle: "Sayt yangilandi",
    stale: "Sayt yangilandi. Sahifani qayta yuklang.",
    reload: "Qayta yuklash",
    generic: "Nimadir notoʻgʻri ketdi",
    genericText: "Amal bajarilmadi. Qayta urinib koʻring.",
    retry: "Qayta urinish",
    previewReadOnly: "Sinov nusxasida oʻzgartirish oʻchirilgan: saytning asosiy manzilida ishlang.",
  },
} as const;
