/** Yangiliklar roʻyxati va tahrir oynasi matnlari (panel bir tilli: oʻzbek lotini). */
export const NEWS_COPY = {
  list: {
    caption: "Saytdagi yangiliklar, eng yangisi birinchi",
    add: "Yangilik qoʻshish",
    empty: "Hali yangilik yoʻq. Birinchisini qoʻshing.",
    columns: {
      title: "Sarlavha",
      status: "Holati",
      date: "Sana",
      photos: "Suratlar",
      updated: "Oʻzgartirilgan",
      actions: "Amallar",
    },
    menu: "{title}: amallar",
    edit: "Tahrirlash",
    open: "Saytda ochish",
    remove: "Oʻchirish",
    many: "Roʻyxat uzun: sahifalarga boʻlish keyingi bosqichda qoʻshiladi.",
    deleteTitle: "Yangilikni oʻchirish",
    deleteText:
      "«{title}» oʻchiriladi va uning beshta tildagi sahifasi 404 qaytaradi. Kerak boʻlsa, Jurnaldan qaytarish mumkin.",
    deleted: "Yangilik oʻchirildi.",
  },
  statusHint: {
    confirmed: "Saytda sana bilan koʻrinadi va qidiruv tizimlariga ochiq.",
    draft: "Saytda koʻrinadi, lekin sanasiz va qidiruvdan yopiq.",
    pending: "Maʼlumot kutilmoqda: saytda sanasiz, qidiruvdan yopiq.",
  },
  editor: {
    createTitle: "Yangilik qoʻshish",
    editTitle: "Yangilikni tahrirlash",
    groups: { publish: "Chop etish", text: "Matn", cover: "Muqova", photos: "Suratlar" },
    status: "Holati",
    date: "Sana",
    slug: "Havola",
    slugHint: "Sarlavhadan avtomatik: kichik lotin harflari, raqam va chiziqcha.",
    slugLocked:
      "Tasdiqlangan yangilik havolasi qulflangan: u allaqachon tarqalgan boʻlishi mumkin.",
    slugEdit: "Havolani oʻzgartirish",
    slugWarning:
      "Saqlangach eski havola yangisiga doimiy (308) yoʻnaltiriladi: tarqalgan havolalar ishlayveradi.",
    slugChecking: "Tekshirilmoqda…",
    slugFree: "Havola boʻsh.",
    slugSuffixed: "Asl havola band edi: oxiriga raqam qoʻshildi.",
    slugPath: "Manzil: {path}",
    topic: "Mavzu",
    topicHint: "Qisqa yorliq, masalan: Tadbir.",
    title: "Sarlavha",
    titleHint: "60 belgigacha: qidiruv natijasida toʻliq koʻrinadi.",
    lead: "Qisqa matn",
    leadHint: "155 belgigacha: roʻyxatda va ulashishda chiqadi.",
    body: "Matn",
    bodyHint: "Xatboshilarni boʻsh qator bilan ajrating.",
    paragraphs: "Xatboshilar: {n}",
    quote: "Iqtibos",
    quoteHint: "Ixtiyoriy. Yozilsa, beshta tilda kerak.",
    color: "Rang",
    colorHint: "Mavzu yorligʻining rangi.",
    swatch: "{n}-rang",
    cover: "Muqova",
    coverHint: "Saytda 3:2 nisbatda koʻrinadi.",
    coverEmpty: "Muqova tanlanmagan: saytda uning oʻrnida belgi turadi.",
    coverAlt: "Muqova tavsifi",
    coverAltHint: "Koʻrmaydiganlar uchun. Boʻsh qolsa, sarlavha ishlatiladi.",
    coverRemove: "Olib tashlash",
    photos: "Suratlar",
    photosHint: "Maqolada muqovadan keyin varaqlanadi.",
    photosEmpty: "Qoʻshimcha surat yoʻq.",
    photoN: "{n}-surat",
    photoUp: "{n}-suratni oldinga surish",
    photoDown: "{n}-suratni orqaga surish",
    photoRemove: "{n}-suratni olib tashlash",
    photoMoved: "Surat {to}-oʻringa koʻchirildi.",
    photoRemoved: "Surat olib tashlandi.",
  },
  locale: {
    auto: "avto",
    manual: "qoʻlda",
    stale: "Oʻzbekcha matn oʻzgardi: bu qatorni qayta oʻgirasizmi?",
    retranslit: "Qayta oʻgirish",
    over: "{max} belgidan uzun: qidiruvda qisqartiriladi.",
    tabs: "Matn tillari",
    empty: "boʻsh",
  },
  save: {
    region: "Saqlash",
    clean: "Oʻzgarish yoʻq",
    dirty: "Oʻzgarishlar saqlanmagan",
    saving: "Saqlanmoqda…",
    saved: "Saqlandi · saytda bir necha soniyada",
    invalid: "Saqlanmadi: belgilangan maydonlarni toʻgʻrilang ({n}).",
    conflict: "Bu yozuv boshqa oynada oʻzgartirilgan. Sahifani yangilang.",
    uploading: "Rasmlar yuklanmoqda: tugashini kuting.",
    view: "Saytda koʻrish",
    newTab: "yangi oynada ochiladi",
    save: "Saqlash",
    leave: "Saqlanmagan oʻzgarishlar bor.",
  },
  errors: {
    required: "{lang}: toʻldiring.",
    slugEmpty: "Havola boʻsh: avval oʻzbekcha sarlavhani yozing.",
    slugShape: "Faqat kichik lotin harflari, raqam va chiziqcha.",
    slugTaken: "Bu havola boshqa yangilikda band.",
    date: "Sanani kiriting.",
    photosMax: "Koʻpi bilan {max} ta surat.",
    notFound: "Yangilik topilmadi: u boshqa oynada oʻchirilgan boʻlishi mumkin.",
    media: "Tanlangan rasm topilmadi: u oʻchirilgan boʻlishi mumkin.",
    denied: "Ruxsat yoʻq: panelga qayta kiring.",
    generic: "Saqlanmadi. Qayta urinib koʻring.",
  },
} as const;
