/** Rahbariyat, ekspertlar va hamkorlar boʻlimlari matnlari (panel bir tilli: oʻzbek lotini). */
export const PEOPLE_COPY = {
  kinds: {
    leader: {
      title: "Rahbariyat",
      add: "Rahbar qoʻshish",
      createTitle: "Rahbar qoʻshish",
      editTitle: "Rahbarni tahrirlash",
      caption: "Rahbariyat, saytdagi tartibda",
      empty: "Hali rahbar qoʻshilmagan.",
      home: "Birinchi uchtasi bosh sahifadagi odamlar boʻlimida ham chiqadi.",
      deleteTitle: "Rahbarni oʻchirish",
    },
    expert: {
      title: "Ekspertlar",
      add: "Ekspert qoʻshish",
      createTitle: "Ekspert qoʻshish",
      editTitle: "Ekspertni tahrirlash",
      caption: "Ekspertlar kengashi, saytdagi tartibda",
      empty: "Hali ekspert qoʻshilmagan.",
      home: "Birinchi uchtasi bosh sahifadagi odamlar boʻlimida ham chiqadi.",
      deleteTitle: "Ekspertni oʻchirish",
    },
  },
  list: {
    order: "Tartibni oʻq tugmalari bilan oʻzgartiring: u darhol saqlanadi.",
    position: "{n}-oʻrin",
    up: "{name}: yuqoriga surish",
    down: "{name}: pastga surish",
    moved: "{name} {n}-oʻringa koʻchirildi.",
    saving: "Tartib saqlanmoqda…",
    saved: "Tartib saqlandi.",
    stale: "Roʻyxat boshqa oynada oʻzgargan. Sahifani yangilang.",
    menu: "{name}: amallar",
    edit: "Tahrirlash",
    open: "Saytda ochish",
    remove: "Oʻchirish",
    deleteText:
      "«{name}» saytdan darhol olib tashlanadi. Kerak boʻlsa, Jurnaldan qaytarish mumkin.",
    noName: "Ism kutilmoqda",
  },
  editor: {
    groups: { main: "Asosiy", photo: "Surat", logo: "Logotip" },
    status: "Holati",
    name: "Ism",
    nameHint:
      "Tasdiqlangan holatda majburiy. Boʻsh qolsa, saytda ism oʻrnida vaqtinchalik matn turadi.",
    role: "Lavozim",
    roleHint: "Masalan: Ijrochi direktor.",
    field: "Soha",
    fieldHint: "Ixtiyoriy. Ekspert kartasida lavozim oʻrnida chiqadi, masalan: Teatr.",
    bio: "Maʼlumot",
    bioHint: "Ixtiyoriy. Tasdiqlangan ekspert kartasidan ochiladigan oynada chiqadi.",
    email: "Elektron pochta",
    emailHint: "Ixtiyoriy. Saytda faqat tasdiqlangan holatda koʻrinadi.",
    photo: "Surat",
    photoHint:
      "Saytda 4:5 nisbatda, faqat tasdiqlangan holatda. Yuz ramkaning yuqori qismida boʻlsin.",
    photoEmpty: "Surat tanlanmagan: saytda uning oʻrnida belgi turadi.",
    remove: "Olib tashlash",
  },
  statusHint: {
    person: {
      confirmed: "Saytda ism, surat va email bilan koʻrinadi, qidiruv tizimlariga ochiq.",
      draft: "Saytda ism va lavozim koʻrinadi, surat va email yashirin. Sahifa qidiruvdan yopiq.",
      pending: "Maʼlumot kutilmoqda: surat va email yashirin, sahifa qidiruvdan yopiq.",
    },
    partner: {
      confirmed: "Hamkorlar sahifasida; logotipi boʻlsa, bosh sahifadagi maydonga ham kiradi.",
      draft: "Hamkorlar sahifasida koʻrinadi, bosh sahifada yoʻq. Sahifa qidiruvdan yopiq.",
      pending: "Saytda koʻrinmaydi: maʼlumot kutilmoqda.",
    },
  },
  partners: {
    title: "Hamkorlar",
    add: "Hamkor qoʻshish",
    createTitle: "Hamkor qoʻshish",
    editTitle: "Hamkorni tahrirlash",
    caption: "{group}, saytdagi tartibda",
    empty: "Hali hamkor qoʻshilmagan.",
    groupEmpty: "Bu guruhda hamkor yoʻq.",
    home: "Bosh sahifadagi hamkorlar maydoni logotipli tasdiqlangan hamkorlar kamida oltita boʻlganda chiqadi. Hozir: {n}.",
    order: "Guruhlar saytdagi tartibda. Guruh ichidagi tartibni oʻq tugmalari bilan oʻzgartiring.",
    deleteTitle: "Hamkorni oʻchirish",
    noLogo: "Logotip yoʻq",
    name: "Nomi",
    nameHint: "Tasdiqlangan va qoralama holatda majburiy: logotip tavsifi ham shundan.",
    group: "Guruh",
    logoHint:
      "Shaffof fonli PNG yoki WebP. Saytda qorongʻi plitkada oq rangda, ustiga kelganda asl rangida.",
    logoAccept: "PNG yoki WebP, 25 MB gacha.",
    logoEmpty: "Logotip tanlanmagan: saytda plitkada nomi yoziladi.",
    plain: "Saytda",
    hover: "Ustiga kelganda",
    href: "Sayt",
    hrefHint: "Ixtiyoriy. https:// bilan boshlanadigan toʻliq manzil.",
  },
  order: {
    "people:leader": "Rahbariyat tartibi",
    "people:expert": "Ekspertlar tartibi",
    partners: "Hamkorlar tartibi",
    milestones: "Tarix tartibi",
  } as Readonly<Record<string, string>>,
  errors: {
    email: "Email notoʻgʻri. Masalan: ism@tashkilot.uz",
    hrefScheme: "Manzil https:// bilan boshlanishi kerak.",
    hrefShape: "Manzil notoʻgʻri.",
    notFound: "Yozuv topilmadi: u boshqa oynada oʻchirilgan boʻlishi mumkin.",
    invalid: "Saqlanmadi: maʼlumotlar bazasi qiymatni qabul qilmadi. Maydonlarni tekshiring.",
    restoreOrder: "Roʻyxat oʻshandan beri oʻzgargan: bu tartibni qaytarib boʻlmaydi.",
  },
} as const;
