/** Media kutubxonasi, Matnlar va Xavfsizlik boʻlimlari matnlari (panel bir tilli: oʻzbek lotini). */
export const SYSTEM_COPY = {
  media: {
    intro: "Saytdagi barcha rasm va videolar: oʻlchami, hajmi va necha joyda ishlatilgani.",
    upload: "Yuklash",
    uploadLabel: "Rasmlar yuklash",
    uploadHint:
      "Yuklangan rasm yangilik yoki boshqa boʻlimda tanlanmaguncha «Ishlatilmagan» boʻlib turadi.",
    filter: "Koʻrsatish",
    all: "Hammasi",
    unused: "Ishlatilmagan",
    count: "{n} ta fayl",
    empty: "Hali fayl yoʻq.",
    emptyUnused: "Ishlatilmagan fayl yoʻq: hammasi saytda turibdi.",
    staticNote:
      "Oʻchirish faqat ishlatilmagan yuklangan faylda. «Kodda» belgili fayllar sayt kodi bilan keladi: ular panel orqali oʻchirilmaydi.",
    caption: "Media fayllar",
    video: "Video",
    inCode: "Kodda",
    uses: "{n} joyda ishlatilgan",
    notUsed: "Ishlatilmagan",
    dims: "{w} × {h}",
    remove: "Oʻchirish",
    removeLabel: "{name}: oʻchirish",
    removeTitle: "Faylni oʻchirish",
    removeText:
      "«{name}» butunlay oʻchiriladi: bazadagi yozuv va serverdagi barcha oʻlchamdagi nusxalari. Buni qaytarib boʻlmaydi.",
    removed: "«{name}» oʻchirildi.",
    removedLeft:
      "«{name}» yozuvi oʻchirildi, lekin serverdagi nusxalarning bir qismi qoldi. Ular saytda ishlatilmaydi.",
    reasonStatic: "Sayt kodidagi fayl: faqat kod orqali oʻchiriladi.",
    errors: {
      notFound: "Fayl topilmadi: u boshqa oynada oʻchirilgan boʻlishi mumkin.",
      inUse: "Fayl hali ishlatilmoqda: avval u yerdan olib tashlang.",
      generic: "Oʻchirib boʻlmadi. Qayta urinib koʻring.",
    },
  },
  texts: {
    intro:
      "Saytdagi yozuvlar: sarlavhalar, tugmalar, izohlar va qidiruv tizimlari uchun sarlavha va tavsiflar. Oʻzgartirilgan matn beshta tilda saqlanadi, asliga istalgan vaqtda qaytariladi.",
    search: "Qidirish",
    searchHint: "Kalit yoki matn boʻyicha, istalgan tilda.",
    onlyChanged: "Faqat oʻzgartirilganlar",
    found: "Topildi: {n} ta matn",
    none: "Hech narsa topilmadi.",
    changed: "Oʻzgartirilgan",
    list: "Roʻyxat",
    seo: "SEO",
    namespaces: {
      common: "Umumiy",
      nav: "Menyu",
      appearance: "Koʻrinish paneli",
      footer: "Sahifa osti",
      meta: "SEO: sarlavha va tavsif",
      errors: "Xato sahifalari",
      home: "Bosh sahifa",
      about: "Biz haqimizda",
      projects: "UPOP TREND",
      news: "Yangiliklar",
      people: "Rahbariyat va ekspertlar",
      partners: "Hamkorlar",
      contacts: "Aloqa",
      privacy: "Maxfiylik",
    },
    editTitle: "Matnni tahrirlash",
    back: "Barcha matnlar",
    bundledTitle: "Asl matn",
    value: "Matn",
    valueHint: "Saytda shu kalit oʻrnida chiqadi.",
    listHint: "Har band alohida: bandlarni boʻsh qator bilan ajrating.",
    tokensHint:
      "Jingalak qavs ichidagi {tokens} saytda qiymat bilan almashadi: ularni oʻchirmang va tarjima qilmang.",
    titleHint: "60 belgigacha: qidiruv natijasida toʻliq koʻrinadi.",
    descriptionHint: "155 belgigacha: qidiruv natijasida sarlavha ostida chiqadi.",
    bundledHint: "Repodagi lugʻatdagi matn. «Asliga qaytarish» saytga shuni qaytaradi.",
    overridden: "Bu matn paneldan oʻzgartirilgan.",
    restore: "Asliga qaytarish",
    restoreTitle: "Asl matnga qaytarish",
    restoreText:
      "Paneldagi oʻzgarish oʻchadi va saytda beshta tilda asl matn chiqadi. Oʻzgarish jurnalda qoladi.",
    restored: "Asl matn qaytarildi · saytda bir necha soniyada",
    errors: {
      required: "{lang}: toʻldiring.",
      missing: "{lang}: {tokens} tushib qolgan.",
      extra: "{lang}: {tokens} asl matnda yoʻq.",
      notFound: "Bunday kalit lugʻatda yoʻq.",
      generic: "Saqlanmadi. Qayta urinib koʻring.",
      restoreFailed: "Qaytarib boʻlmadi. Qayta urinib koʻring.",
    },
  },
  security: {
    account: "Hisob",
    email: "Elektron pochta",
    lastSignIn: "Oxirgi kirish",
    unknown: "nomaʼlum",
    sessions: "Sessiyalar",
    sessionsText:
      "Panelga kirilgan hamma qurilmadan, shu jumladan shu qurilmadan chiqariladi. Boshqa qurilmada ochiq qolgan oyna koʻpi bilan bir soatda yopiladi.",
    signOutAll: "Hamma qurilmalardan chiqish",
    signOutTitle: "Hamma qurilmalardan chiqish",
    signOutText:
      "Hamma sessiya bekor qilinadi va kirish sahifasi ochiladi. Davom etish uchun parol bilan qayta kirasiz.",
    password: "Parol",
    passwordText:
      "Parol panelda emas, Supabase boshqaruv panelida almashtiriladi: Authentication → Users boʻlimida hisobingizni oching va yangi parol oʻrnating yoki tiklash xatini yuboring.",
    passwordAfter:
      "Parol almashgach shu yerda «Hamma qurilmalardan chiqish» ni bosing va yangi parol bilan kiring.",
  },
} as const;
