/** Aloqa va Tarix boʻlimlari, ularning umumiy xatolari va jurnaldan qaytarish matnlari. */
export const ORG_COPY = {
  status: "Holati",
  statusOf: "{field}: holati",
  moveUp: "{item}: yuqoriga",
  moveDown: "{item}: pastga",
  moved: "{item} {to}-oʻringa koʻchirildi.",
  contacts: {
    warning:
      "Aloqa maʼlumotlari saytning har bir sahifasida (pastki qismda va qidiruv tizimlari uchun belgilarda) chiqadi: saqlash hamma sahifani yangilaydi.",
    statusHint:
      "Tasdiqlangan maʼlumot qidiruv tizimlariga ham beriladi; kutilmoqda: hali aniq emas.",
    groups: {
      address: "Manzil",
      reach: "Telefon, pochta va Telegram",
      hours: "Ish vaqti va xarita",
      socials: "Ijtimoiy tarmoqlar",
    },
    address: "Manzil",
    addressHint: "Toʻliq manzil: indeks, shahar, tuman, koʻcha va uy.",
    postalCode: "Pochta indeksi",
    postalCodeHint: "Olti raqam, masalan 100011.",
    locality: "Shahar (lotincha)",
    localityHint: "Qidiruv tizimlari uchun, masalan Tashkent.",
    phones: "Telefonlar",
    phonesHint: "+998 XX XXX XX XX shaklida saqlanadi. Birinchisi sayt pastida ham chiqadi.",
    phoneN: "{n}-telefon",
    phoneAdd: "Telefon qoʻshish",
    phoneRemove: "{n}-telefonni olib tashlash",
    phoneRemoved: "Telefon olib tashlandi.",
    phonesEmpty: "Telefon kiritilmagan.",
    email: "Elektron pochta",
    telegram: "Telegram",
    telegramHint: "https://t.me/… havolasi yoki @nom.",
    hours: "Ish vaqti",
    hoursHint: "Masalan: Dushanba–juma, 9:00–18:00.",
    map: "Xarita",
    mapHint:
      "Kenglik va uzunlik (Yandex yoki Google xaritasidan). Boʻsh qolsa, xarita havolasi manzil boʻyicha qidiradi.",
    lat: "Kenglik",
    lng: "Uzunlik",
    socialsHint: "Havolasi boʻsh tarmoq saytdan olib tashlanadi. Tartib saytdagi tartib.",
    socialHref: "Havola",
    socialLabel: "Yorliq",
    networks: {
      telegram: "Telegram",
      instagram: "Instagram",
      youtube: "YouTube",
      facebook: "Facebook",
    },
  },
  history: {
    note: "Saytda faqat tasdiqlangan va yili yozilgan bosqichlar koʻrinadi, shu roʻyxatdagi tartibda.",
    empty: "Hali bosqich yoʻq. Birinchisini qoʻshing.",
    add: "Bosqich qoʻshish",
    added: "Yangi bosqich roʻyxat oxiriga qoʻshildi.",
    row: "{n}-bosqich",
    fresh: "yangi",
    year: "Yil",
    yearHint: "Toʻrt raqam, masalan 2026.",
    title: "Nomi",
    icon: "Belgi",
    remove: "Oʻchirish",
    removeLabel: "{item}ni oʻchirish",
    removeTitle: "Bosqichni oʻchirish",
    removeText:
      "«{title}» bosqichi saytdan olib tashlanadi. Kerak boʻlsa, Jurnaldan qaytarish mumkin.",
    removed: "Bosqich oʻchirildi.",
    icons: {
      calendar: "Taqvim",
      users: "Jamoa",
      building: "Bino",
      star: "Yulduz",
      heart: "Yurak",
      ticket: "Chipta",
      "map-pin": "Joy",
      mic: "Mikrofon",
      mask: "Niqob",
      palette: "Boʻyoqlar",
      film: "Kino",
      play: "Ijro",
      news: "Gazeta",
      projects: "Loyihalar",
      shield: "Qalqon",
    },
  },
  errors: {
    required: "{lang}: toʻldiring.",
    allOrNone: "Yozilsa, beshta tilda kerak ({lang}: boʻsh).",
    confirmedEmpty: "Tasdiqlangan boʻlsa, qiymat kerak.",
    phone: "Raqam +998 XX XXX XX XX shaklida boʻlsin.",
    email: "Elektron pochta manzili notoʻgʻri.",
    telegram: "https://t.me/ bilan boshlanadigan havola yoki @nom kiriting.",
    https: "https:// bilan boshlanadigan havola kiriting.",
    label: "Yorliqni yozing.",
    postalCode: "Olti raqam kiriting.",
    locality: "80 belgigacha, lotin harflarida.",
    mapPair: "Kenglik ham, uzunlik ham kerak.",
    lat: "Kenglik −90 dan 90 gacha.",
    lng: "Uzunlik −180 dan 180 gacha.",
    year: "Yil 1990 dan 2100 gacha.",
    order: "Roʻyxat boshqa oynada oʻzgargan. Sahifani yangilang.",
    notFound: "Yozuv topilmadi: u boshqa oynada oʻchirilgan boʻlishi mumkin.",
    media: "Tanlangan fayl topilmadi: u oʻchirilgan boʻlishi mumkin.",
    denied: "Ruxsat yoʻq: panelga qayta kiring.",
    generic: "Saqlanmadi. Qayta urinib koʻring.",
  },
  restore: {
    failed: "Qaytarib boʻlmadi: bu orada yozuv oʻzgargan yoki bogʻliq fayl oʻchirilgan.",
  },
  journal: {
    contacts: "Aloqa maʼlumotlari",
    socials: "Ijtimoiy tarmoqlar",
    gallery: "UPOP galereyasi",
    order: "Tartib",
    orders: {
      milestones: "Tarix",
      partners: "Hamkorlar",
      leader: "Rahbariyat",
      expert: "Ekspertlar",
    },
  },
} as const;
